# Generated by Django 5.0.1 on 2024-06-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AhsPropertyLottery2',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('development', models.CharField(blank=True, db_column='Development', max_length=255, null=True)),
                ('bed', models.IntegerField(blank=True, db_column='Bed', null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='Start_Date', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='End_Date', null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('omv', models.CharField(blank=True, db_column='OMV', max_length=255, null=True)),
                ('sale_price', models.CharField(blank=True, db_column='Sale_Price', max_length=255, null=True)),
                ('propertyid', models.CharField(blank=True, db_column='PropertyID', max_length=255, primary_key=True, serialize=False)),
                ('phase', models.CharField(blank=True, db_column='Phase', max_length=255, null=True)),
                ('lotterycase', models.CharField(blank=True, db_column='LotteryCase', max_length=255, null=True)),
                ('lotterydate', models.CharField(blank=True, db_column='LotteryDate', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('equity', models.CharField(blank=True, db_column='Equity', max_length=255, null=True)),
                ('name_date', models.CharField(blank=True, db_column='Name_Date', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ahs_property_lottery_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChAhsSubmissionsLottery2',
            fields=[
                ('applicationid', models.CharField(db_column='ApplicationID', max_length=18, primary_key=True, serialize=False)),
                ('propertyid', models.CharField(blank=True, db_column='PropertyID', max_length=14, null=True)),
                ('applicantname', models.CharField(blank=True, db_column='ApplicantName', max_length=40, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=41, null=True)),
                ('development', models.CharField(blank=True, db_column='Development', max_length=61, null=True)),
                ('stage', models.CharField(blank=True, db_column='Stage', max_length=18, null=True)),
                ('saveurl', models.CharField(blank=True, db_column='SaveURL', max_length=1, null=True)),
                ('applicationurl', models.CharField(blank=True, db_column='ApplicationURL', max_length=1, null=True)),
                ('responseurl', models.CharField(blank=True, db_column='ResponseURL', max_length=1, null=True)),
                ('ucrn', models.FloatField(blank=True, db_column='UCRN', null=True)),
                ('propertyname', models.CharField(blank=True, db_column='PropertyName', max_length=105, null=True)),
                ('submitdate', models.CharField(blank=True, db_column='SubmitDate', max_length=11, null=True)),
                ('adults', models.BigIntegerField(blank=True, db_column='Adults', null=True)),
                ('kids', models.BigIntegerField(blank=True, db_column='Kids', null=True)),
                ('joint', models.CharField(blank=True, db_column='Joint', max_length=4, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=6, null=True)),
                ('relationship', models.CharField(blank=True, db_column='Relationship', max_length=11, null=True)),
                ('household_size', models.BigIntegerField(blank=True, db_column='Household_Size', null=True)),
                ('jointname', models.CharField(blank=True, db_column='JointName', max_length=8, null=True)),
                ('mortgageprovider', models.CharField(blank=True, db_column='MortgageProvider', max_length=26, null=True)),
                ('resident', models.CharField(blank=True, db_column='Resident', max_length=4, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=22, null=True)),
                ('residentvalid', models.CharField(blank=True, db_column='ResidentValid', max_length=1, null=True)),
                ('incomevalid', models.CharField(blank=True, db_column='IncomeValid', max_length=1, null=True)),
                ('depositvalid', models.CharField(blank=True, db_column='DepositValid', max_length=1, null=True)),
                ('equityvalid', models.CharField(blank=True, db_column='EquityValid', max_length=1, null=True)),
                ('mortgageamount', models.CharField(blank=True, db_column='MortgageAmount', max_length=1, null=True)),
                ('helpbuyamount', models.CharField(blank=True, db_column='HelpBuyAmount', max_length=1, null=True)),
                ('equity', models.CharField(blank=True, db_column='Equity', max_length=1, null=True)),
                ('deposit', models.CharField(blank=True, db_column='Deposit', max_length=1, null=True)),
                ('incomeoverall', models.CharField(blank=True, db_column='IncomeOverall', max_length=1, null=True)),
                ('jointincomeoverall', models.CharField(blank=True, db_column='JointIncomeOverall', max_length=1, null=True)),
                ('housesizevalid', models.CharField(blank=True, db_column='HouseSizeValid', max_length=1, null=True)),
                ('taskurl', models.CharField(blank=True, db_column='TaskURL', max_length=1, null=True)),
                ('parentid', models.CharField(blank=True, db_column='ParentID', max_length=14, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=1, null=True)),
                ('jointage', models.CharField(blank=True, db_column='JointAge', max_length=1, null=True)),
                ('county', models.CharField(blank=True, db_column='County', max_length=1, null=True)),
                ('indublin', models.CharField(blank=True, db_column='InDublin', max_length=1, null=True)),
                ('mortvalid', models.CharField(blank=True, db_column='MortValid', max_length=1, null=True)),
                ('lotteryposition', models.CharField(blank=True, db_column='LotteryPosition', max_length=1, null=True)),
                ('jointnationality', models.CharField(blank=True, db_column='JointNationality', max_length=1, null=True)),
                ('jointrelationship', models.CharField(blank=True, db_column='JointRelationship', max_length=1, null=True)),
                ('jointemail', models.CharField(blank=True, db_column='JointEmail', max_length=1, null=True)),
                ('appealdate', models.CharField(blank=True, db_column='AppealDate', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ch_ahs_submissions_lottery2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.chahssubmissionslottery2')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.ahspropertylottery2')),
            ],
        ),
    ]
